### ISSUE TITLE
windows平台可以运行的啥时有？

### ISSUE THREAD

**Issue by syc666** [XiaoGaoYang/yiban-api#1]
windows用户表示运行出问题了，肖总啥时搞个windows可以运行的啊？

**Comment by XiaoGaoYang** [comment]
安装模块之前以使用管理员身份执行以下命令可以解决
```
npm install -g node-gyp
npm install -g --add-python-to-path windows-build-tools
```
具体可以参考
[https://github.com/nodejs/node-gyp](https://github.com/nodejs/node-gyp)
[https://github.com/felixrieseberg/windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)
